"""
build_map.py — turn india_boundary.geojson into india.js, a ready-to-draw SVG path.

Conflictscape draws its own map instead of pulling raster tiles: an outline in
the page's own ink, with one mark per record. That means no tile server, no
external stylesheet, no third-party map library, the same picture offline as
online, and a map that follows the light and dark themes like everything else.

The projection is Web Mercator, so the outline sits where readers expect it to.
Coordinates are emitted in a 1000-unit-wide viewBox with two decimals, and
rings are simplified with Ramer–Douglas–Peucker — at the sizes this map is
drawn, the discarded vertices are well under a pixel.

    python build_map.py                 # writes india.js
    python build_map.py --tolerance 0.6 # coarser outline, smaller file

Standard library only.
"""

import argparse
import json
import math
from pathlib import Path

SRC = Path("india_boundary.geojson")
OUT = Path("india.js")
WIDTH = 1000.0


def mercator(lon, lat):
    lat = max(min(lat, 84.0), -84.0)
    x = math.radians(lon)
    y = math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
    return x, y


def rings(geometry):
    """Yields every linear ring in a Polygon or MultiPolygon."""
    kind, coords = geometry["type"], geometry["coordinates"]
    if kind == "Polygon":
        yield from coords
    elif kind == "MultiPolygon":
        for polygon in coords:
            yield from polygon
    else:
        raise ValueError(f"unsupported geometry: {kind}")


def _perp(p, a, b):
    (px, py), (ax, ay), (bx, by) = p, a, b
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def simplify(points, tol):
    """Ramer–Douglas–Peucker, iterative so a long coastline cannot blow the stack."""
    if len(points) < 3 or tol <= 0:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        first, last = stack.pop()
        worst, index = tol, None
        for i in range(first + 1, last):
            d = _perp(points[i], points[first], points[last])
            if d > worst:
                worst, index = d, i
        if index is not None:
            keep[index] = True
            stack.append((first, index))
            stack.append((index, last))
    return [p for p, k in zip(points, keep) if k]


def main():
    ap = argparse.ArgumentParser(description="Build india.js from india_boundary.geojson")
    ap.add_argument("--tolerance", type=float, default=0.35,
                    help="simplification tolerance in viewBox units (default 0.35)")
    ap.add_argument("--min-ring", type=int, default=6,
                    help="drop rings left with fewer points than this (default 6)")
    args = ap.parse_args()

    data = json.loads(SRC.read_text(encoding="utf-8"))
    geometry = data["geometry"] if data.get("type") == "Feature" else data

    projected = [[mercator(lon, lat) for lon, lat, *_ in ring] for ring in rings(geometry)]
    xs = [x for ring in projected for x, _ in ring]
    ys = [y for ring in projected for _, y in ring]
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    scale = WIDTH / (x1 - x0)
    height = (y1 - y0) * scale

    parts, kept, total = [], 0, 0
    for ring in projected:
        pts = [((x - x0) * scale, (y1 - y) * scale) for x, y in ring]
        total += len(pts)
        pts = simplify(pts, args.tolerance)
        if len(pts) < args.min_ring:
            continue
        kept += len(pts)
        head = f"M{pts[0][0]:.2f} {pts[0][1]:.2f}"
        tail = "".join(f"L{x:.2f} {y:.2f}" for x, y in pts[1:])
        parts.append(head + tail + "Z")

    path = "".join(parts)
    OUT.write_text(
        "/* Generated by build_map.py from india_boundary.geojson — do not edit by hand.\n"
        "   Web Mercator, 1000-unit viewBox. Source outline: see gazetteer_source.json. */\n"
        "window.INDIA_MAP = {\n"
        f'  "width": {WIDTH:.0f},\n'
        f'  "height": {height:.2f},\n'
        f'  "bounds": {{"west": {math.degrees(x0):.6f}, "east": {math.degrees(x1):.6f}, '
        f'"south": {math.degrees(2 * math.atan(math.exp(y0)) - math.pi / 2):.6f}, '
        f'"north": {math.degrees(2 * math.atan(math.exp(y1)) - math.pi / 2):.6f}}},\n'
        f'  "path": "{path}"\n'
        "};\n",
        encoding="utf-8",
    )
    print(f"{OUT}: {len(parts)} rings, {kept} of {total} points kept "
          f"({kept / total:.0%}), {OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
