/* Superseded by app.js.

   This file held the Leaflet-based map controller for the previous build.
   Conflictscape now draws its own India outline from india.js (generated by
   build_map.py) and runs the whole page from app.js, so there is no Leaflet
   dependency, no tile server and no third-party stylesheet. index.html no
   longer loads this file; it will be deleted once nothing references it. */
